### PR TITLE
Allow connection from patched instance (with `isv_svn` + 1)

### PR DESCRIPTION
**Pull request by tobin-crypto**
Modify verification code. Allow an upgraded instance to connect to an
instance running the previous svn versioned software.

Add a bunch of `trace!` statements and modify the verification logic.

Verification happens on both client and server side, we control the
verification logic with `mr_enclave`, and `previous_mr_enclave`.

- With no `mr_enclave` we verify if:
  - `isv_svn`s match

- With `mr_enclave` we verify if:
  - `isv_svn`s match and `mr_enclave`s match
  - peer's `isv_svn` is one bigger than ours (no check on `mr_enclave`,
    this is used during upgrade by the server).

- With `previous_mr_enclave` we verify if:
  - Our `isv_svn` is one bigger than peer and the `previous_mr_enclave`
    is equal to the `mr_enclave` of peer (this is used by client during
    upgrade).

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/chain/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [x] Have you rebased your work on top of the latest master? 
- [x] Have you checked your code compiles? (`cargo build`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`cargo test`)
- [x] Have you checked your code formatting is correct? (`cargo fmt -- --check --color=auto`)
- [x] Have you checked your basic code style is fine? (`cargo clippy`)
- [x] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`cargo audit`)
- [ ] If your changes affect the client infrastructure, have you run the [integration test](https://github.com/crypto-com/chain/tree/master/integration-tests)?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/chain/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/chain/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/chain/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Review by devashishdxt — COMMENTED** [review]
There are some unrelated clippy failures.

**Comment by tomtau** [comment]
bors try

**Review by tomtau — CHANGES_REQUESTED** [review]
looks ok... the clippy warnings are irrelevant to this and have been on the now passively maintained repo for a while.

can you squash the commits?

**Comment by tobin-crypto** [comment]
> looks ok... the clippy warnings are irrelevant to this and have been on the now passively maintained repo for a while.
> 
> can you squash the commits?

Sure thing, done.

**Comment by tobin-crypto** [comment]
I just want to highlight the fact that this PR makes logic changes to the verification algorithm. I have stripped the old and new code down, added some comments, and will post here just to make sure everything is ok. Please note, this snippet shows that this PR adds the code that allows `case B` to pass verification, for the Vault code this is needed because when setting up a connection using remote attestation we have _both_ the client and the server verify the cert of the other. I write this because I do not know how the code was intended to be used or how it is currently used by other users of this library.
```
// Patched logic. Note, explicit Err implicit Ok.
fn verify() {
    // Remember, enclave_info is for the host running this code, the quote is from the peer.
    match (
        enclave_info.isv_svn,
        enclave_info.mr_enclave,
        enclave_info.previous_mr_enclave,
    ) {
        // Current Vault code does not use this match arm.
        (isv_svn, None, _) => {
            if isv_svn != quote.report_body.isv_svn {
                return Err(EnclaveCertVerifierError::SvnMismatch);
            }
        }
        // For Vault code this match arm is used in two circumstances
        // A. by both client/server when versions are the same.
        // B. by server when client is upgraded.
        // Ok if one of:
        //   - Some(mr_enclave) AND isv_svn matches AND mr_enclave matches (case A).
        //   - Some(mr_enclave) AND isv_svn of host is one less than peer (case B).
        (isv_svn, Some(mr_enclave), None) => {
            if isv_svn == quote.report_body.isv_svn {
                if mr_enclave != quote.report_body.measurement.mr_enclave {
                    return Err(EnclaveCertVerifierError::MeasurementMismatch);
                }
            } else if isv_svn != quote.report_body.isv_svn - 1 {
                return Err(EnclaveCertVerifierError::SvnMismatch);
            }
        }
        // This match arm is used by client when client is upgraded.
        // Ok iff Some(previous_mr_enclave) AND isv_svn of host is one bigger
        // than peer AND previous_mr_enclave (of host) matches mr_enclave of peer
        (isv_svn, Some(_), Some(previous_mr_enclave)) => {
            if isv_svn - 1 != quote.report_body.isv_svn {
                return Err(EnclaveCertVerifierError::MeasurementMismatch);
            }
            if previous_mr_enclave != quote.report_body.measurement.mr_enclave {
                return Err(EnclaveCertVerifierError::MeasurementMismatch);
            }
        }
    }
    Ok(())
}

// Un-patched logic. Note, explicit Ok implicit Err.
fn verify() {
    match (
        enclave_info.isv_svn,
        enclave_info.mr_enclave,
        enclave_info.previous_mr_enclave,
    ) {
        // Ok iff no mr_enclave AND isv_svn matches.
        (isv_svn, None, _) if isv_svn == quote.report_body.isv_svn => Ok(()),
        // Ok iff Some(mr_enclave) AND isv_svn matches AND mr_enclave matches.
        (isv_svn, Some(mr_enclave), _)
            if isv_svn == quote.report_body.isv_svn
                && mr_enclave == quote.report_body.measurement.mr_enclave =>
        {
            Ok(())
        }
        // Ok iff Some(previous_mr_enclave) AND isv_svn of host is one bigger
        // than peer AND previous_mr_enclave (of host) matches mr_enclave of peer.
        (isv_svn, _, Some(previous_mr_enclave))
            if isv_svn - 1 == quote.report_body.isv_svn
                && previous_mr_enclave == quote.report_body.measurement.mr_enclave =>
        {
            Ok(())
        }
        _ => Err(EnclaveCertVerifierError::MeasurementMismatch),
    }?
}
```

If you see any mistakes, ether in the snippet or in how we are using the library, please say so.

Thanks

**Comment by tobin-crypto** [comment]
I'm not convinced with this solution. With this applied the security of the system using this library shifts to the software signing key. Please do not merge this until its better thought through.

**Comment by tomtau** [comment]
@tobin-crypto the _production_ software signing key _shouldn't be on the running system_ -- the official recommendations are to have it on cold HSM, have separate development and production environments, secure auditable procedures around the production code signing etc.


just to clarify on the original intended use cases -- in the original code, there are 3 enclaves:  https://github.com/crypto-com/thaler-docs/blob/master/docs/modules/tdbe.md#svn-verification--compilation-order with different use cases that communicate to each other (enclave0, enclave1, enclave2)

Case 0 -- used by enclave0 on the client side when talking to enclave1/enclave2 (as it can't know mr_enclave value of enclave1/enclave2, as they are compiled after it)
Case 1 -- used by two same enclaves when talking to each other (they'd set mr_enclave to the one they found in their self-report), or by non-enclave client code when talking to an enclave server (just set the value to the expected one), or by e.g. enclave1 when talking to enclave0 (as it can know its value)
Case 2 -- used for the transitional period in upgrades e.g. newer enclave0 talking to one older version of itself

**Comment by tobin-crypto** [comment]
> the production software signing key shouldn't be on the running system 

lolz, I should hope not :)

**Comment by tobin-crypto** [comment]
> Case 0 -- used by enclave0 on the client side when talking to enclave1/enclave2 (as it can't know mr_enclave value of enclave1/enclave2, as they are compiled after it)
Case 1 -- used by two same enclaves when talking to each other (they'd set mr_enclave to the one they found in their self-report), or by non-enclave client code when talking to an enclave server (just set the value to the expected one), or by e.g. enclave1 when talking to enclave0 (as it can know its value)
Case 2 -- used for the transitional period in upgrades e.g. newer enclave0 talking to one older version of itself

Thanks for the explanation. So if I understand your use case correctly I think we can apply this PR without breaking anything.

**Comment by tobin-crypto** [comment]
Converting to draft while I fix the unrelated clippy warnings etc.

**Comment by tomtau** [comment]
> Thanks for the explanation. So if I understand your use case correctly I think we can apply this PR without breaking anything.

Yeah, it should be fine -- the integration tests seem to pass and this is passively maintained for the moment.

**Comment by tobin-crypto** [comment]
> Yeah, it should be fine -- the integration tests seem to pass and this is passively maintained for the moment.

I'm working on just stealing all your code out of `thaler/chain-tx-enclave-next/enclave-ra/` and creating a repo at `monacohq/enclane-ra` with a single commit and a commit log stating where the code came from (tree, branch, commit) and a list of contributing authors. Next I plan on tearing it apart, creating a crate for the sp stuff and a couple of modules for the client/server (`ra-client/`, ra-enclave/` respectively) and putting all that under the `monacohq/sgx-comm` repository. I'll attribute in a commit or in some docs in `sgx-comm` also). Finally I'll archive `monacohq/ra-enclave`. All the while keeping our vault code building. 

That's the plan. Please let me know if this bothers you or if there is anything more you'd like me to do to give due attribution.

Thanks.

**Pull request closed without merging**
